# Generated by Django 5.2.7 on 2025-10-30 05:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upohars", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upoharimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
