# Generated by Django 5.2.7 on 2025-10-26 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upohars", "0002_upoharrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
    ]
