# Generated by Django 5.2.7 on 2025-10-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upohars", "0003_remove_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
